version: "3"
services:
  traefik:
    image: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./acme.json:/etc/traefik/acme.json

  mysql:
    image: mariadb:10.4
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - dac_override
      - setuid
      - setgid
    environment:
      - MYSQL_ROOT_PASSWORD=abcde123
    volumes:
      - db_data:/var/lib/mysql

  tika:
    image: sutoj/tika
    restart: unless-stopped
    cap_drop:
      - ALL
    deploy:
      resources:
        reservations:
          memory: 512M
        limits:
          memory: 512M

  memcached:
    image: memcached:latest
    restart: unless-stopped
    cap_drop:
      - ALL
    command: -m 64

  piler:
    image: sutoj/piler-ee:1.5.0
    init: true
    environment:
      - MYSQL_PILER_PASSWORD=piler123
      - MYSQL_ROOT_PASSWORD=abcde123
      - MYSQL_HOSTNAME=mysql
      - TIKA_HOSTNAME=tika
      - PILER_HOSTNAME=archive.yourdomain.com
      - MULTITENANCY=0
      - MEMCACHED_HOSTNAME=memcached
      - NODE_TYPE=WORKER
    ports:
      - "25:25"
    volumes:
      - piler_etc:/etc/piler
      - piler_var:/var/piler
      - ./piler.lic:/etc/piler/piler.lic:ro
    healthcheck:
      test: curl -s smtp://localhost/
      interval: "60s"
      timeout: "3s"
      start_period: "15s"
      retries: 3
    deploy:
      resources:
        reservations:
          memory: 512M
        limits:
          memory: 512M

    depends_on:
      - "memcached"
      - "mysql"
      - "tika"

volumes:
  db_data: {}
  piler_etc: {}
  piler_var: {}
